import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/component/Navbar";
import Footer from "@/component/Footer";
import { ToastContainer } from "react-toastify";
import Providers from "@/lib/providers/page";
import 'animate.css';
import SmoothScroll from "@/component/SmoothScroll";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "QurbaniHat",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <SmoothScroll></SmoothScroll>
        <Navbar></Navbar>
        <Providers>
          <main className="w-[90%] mx-auto">{children}</main>
        </Providers>
        <Footer></Footer>
        <ToastContainer />
        </body>
    </html>
  );
}
